### ISSUE TITLE
Style of coding

### ISSUE THREAD

**Issue by Vanya112** [AlexAist/TRiTPO-Project#1]
1. Пропустил строки там, где не надо их пропускать в ClassMainActivity (line 29, line 194)
2. Пропустил пробел после знака "=" в ClassMainActivity (line 136), в AddCarActivity (line 42)
3. Нежелательно длинные строки (больше 80 символов) в AddCarActivity (line 45, line 44) 
4. Не пропустил строку между полями класса AddCarActivity и первым методом класса.
5. Комментарии должны использоваться для предоставления обзоров кода и предоставления дополнительной информации, которая не всегда доступна в самом коде. Комментарии должны содержать только информацию, которая имеет отношение к чтению и пониманию программы. 
У тебя в ClassMainActivity закомментирован местами код программы.
6. Неправильно выровнял длинный запрос к базе данных в ClassMainActivity (line 55)

**Comment by AlexAist** [comment]
Сделал

**Comment by AlexAist** [comment]
Сделал
